import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FaTwitter, FaLinkedinIn, FaGithub, FaLightbulb } from 'react-icons/fa';

const Footer = () => {
    const footerLinks = [
        {
            title: 'Company',
            links: [
                { name: 'About', path: '/about' },
                { name: 'Blog', path: '/blog' },
                { name: 'Careers', path: '#' },
                { name: 'Contact', path: '#' }
            ]
        },
        {
            title: 'Resources',
            links: [
                { name: 'Documentation', path: '#' },
                { name: 'Privacy Policy', path: '#' },
                { name: 'Terms of Service', path: '#' },
                { name: 'FAQ', path: '#' }
            ]
        },
        {
            title: 'Follow Us',
            links: [
                { name: 'Twitter', path: '#', icon: <FaTwitter /> },
                { name: 'LinkedIn', path: '#', icon: <FaLinkedinIn /> },
                { name: 'GitHub', path: '#', icon: <FaGithub /> }
            ]
        }
    ];

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <footer className="bg-gradient-to-b from-gray-900 to-blue-900 text-white relative">
            {/* Decorative Elements */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-30" />
                <div className="absolute -top-24 -right-24 w-48 h-48 bg-blue-500 rounded-full filter blur-3xl opacity-10" />
                <div className="absolute -bottom-20 -left-20 w-60 h-60 bg-indigo-500 rounded-full filter blur-3xl opacity-10" />
            </div>

            <div className="container mx-auto px-4 py-12 relative z-10">
                {/* Top Section */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 mb-10">
                    <div>
                        <Link to="/" className="flex items-center gap-2 mb-6">
                            <motion.div
                                whileHover={{ rotate: 360 }}
                                transition={{ duration: 0.7 }}
                                className="bg-white rounded-full p-2"
                            >
                                <FaLightbulb className="text-blue-600 text-lg" />
                            </motion.div>
                            <span className="font-bold text-xl text-white">
                                Tech<span className="text-blue-300">Insights</span>AI
                            </span>
                        </Link>
                        <p className="text-gray-300 mb-6">
                            Discover the latest insights in technology, generated by AI and curated for tech enthusiasts and forward-thinkers.
                        </p>
                        <div className="flex space-x-4">
                            {[<FaTwitter />, <FaLinkedinIn />, <FaGithub />].map((icon, index) => (
                                <motion.a
                                    key={index}
                                    href="#"
                                    whileHover={{ scale: 1.2, y: -3 }}
                                    whileTap={{ scale: 0.95 }}
                                    className="bg-white/10 text-white hover:bg-blue-600 p-2 rounded-full transition-colors"
                                >
                                    {icon}
                                </motion.a>
                            ))}
                        </div>
                    </div>

                    <motion.div
                        variants={container}
                        initial="hidden"
                        whileInView="show"
                        viewport={{ once: true }}
                        className="col-span-1 md:col-span-3"
                    >
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
                            {footerLinks.map((column, idx) => (
                                <div key={idx}>
                                    <h3 className="font-semibold text-lg mb-4 text-white">{column.title}</h3>
                                    <ul className="space-y-3">
                                        {column.links.map((link, linkIdx) => (
                                            <motion.li key={linkIdx} variants={item}>
                                                <Link
                                                    to={link.path}
                                                    className="text-gray-300 hover:text-blue-300 transition-colors flex items-center gap-2"
                                                >
                                                    {link.icon && <span>{link.icon}</span>}
                                                    {link.name}
                                                </Link>
                                            </motion.li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                        </div>
                    </motion.div>
                </div>

                {/* Newsletter */}
                <motion.div
                    className="bg-white/5 backdrop-blur-sm rounded-2xl p-8 mb-10"
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.2 }}
                >
                    <div className="grid md:grid-cols-5 gap-6 items-center">
                        <div className="md:col-span-3">
                            <h3 className="text-xl font-bold mb-2">Stay up to date</h3>
                            <p className="text-gray-300">Get the latest tech insights delivered straight to your inbox.</p>
                        </div>
                        <div className="md:col-span-2">
                            <form className="flex">
                                <input
                                    type="email"
                                    placeholder="Enter your email"
                                    className="bg-white/10 text-white rounded-l-lg px-4 py-3 flex-grow focus:outline-none focus:ring-2 focus:ring-blue-400"
                                />
                                <motion.button
                                    whileHover={{ scale: 1.05 }}
                                    whileTap={{ scale: 0.95 }}
                                    className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-6 rounded-r-lg transition-colors"
                                >
                                    Subscribe
                                </motion.button>
                            </form>
                        </div>
                    </div>
                </motion.div>

                {/* Bottom Section */}
                <div className="pt-8 border-t border-gray-700/50 flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
                    <p className="text-gray-400 text-sm">
                        &copy; {new Date().getFullYear()} TechInsights AI. All rights reserved.
                    </p>
                    <div className="flex space-x-6">
                        <Link to="#" className="text-gray-400 hover:text-blue-300 text-sm transition-colors">Privacy Policy</Link>
                        <Link to="#" className="text-gray-400 hover:text-blue-300 text-sm transition-colors">Terms of Service</Link>
                        <Link to="#" className="text-gray-400 hover:text-blue-300 text-sm transition-colors">Cookie Policy</Link>
                    </div>
                </div>
            </div>
        </footer>
    );
};

export default Footer;