import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FaTwitter, FaLinkedinIn, FaGithub, FaLightbulb } from 'react-icons/fa';
import ComingSoonPopup from './ComingSoonPopup';

const Footer = () => {
    const [isPopupOpen, setIsPopupOpen] = useState(false);

    const handleSubscribeClick = (e) => {
        e.preventDefault();
        setIsPopupOpen(true);
    };

    const footerLinks = [
        {
            title: 'Company',
            links: [
                { name: 'About', path: '/about' },
                { name: 'Blog', path: '/blog' },
                { name: 'Careers', path: '#' },
                { name: 'Contact', path: '#' }
            ]
        },
        {
            title: 'Resources',
            links: [
                { name: 'Documentation', path: '#' },
                { name: 'Privacy Policy', path: '#' },
                { name: 'Terms of Service', path: '#' },
                { name: 'FAQ', path: '#' }
            ]
        },
        {
            title: 'Follow Us',
            links: [
                { name: 'Twitter', path: 'https://x.com/Yashp010', icon: <FaTwitter /> },
                { name: 'LinkedIn', path: 'https://www.linkedin.com/in/yashparmar010/', icon: <FaLinkedinIn /> },
                { name: 'GitHub', path: 'https://github.com/Yashpsct010', icon: <FaGithub /> }
            ]
        }
    ];

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <>
            <footer className="bg-gradient-to-b from-gray-900 to-blue-900 text-white relative">
                {/* Enhanced Decorative Elements with animations */}
                <div className="absolute inset-0 overflow-hidden pointer-events-none">
                    <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-30" />
                    <motion.div
                        className="absolute -top-24 -right-24 w-32 sm:w-48 h-32 sm:h-48 bg-blue-500 rounded-full filter blur-3xl opacity-10"
                        animate={{
                            y: [0, 15, 0],
                            scale: [1, 1.1, 1],
                        }}
                        transition={{
                            duration: 10,
                            repeat: Infinity,
                            repeatType: "reverse"
                        }}
                    />
                    <motion.div
                        className="absolute -bottom-20 -left-20 w-40 sm:w-60 h-40 sm:h-60 bg-indigo-500 rounded-full filter blur-3xl opacity-10"
                        animate={{
                            y: [0, -15, 0],
                            scale: [1, 1.15, 1],
                        }}
                        transition={{
                            duration: 12,
                            repeat: Infinity,
                            repeatType: "reverse"
                        }}
                    />
                </div>

                <div className="container mx-auto px-4 py-10 sm:py-12 relative z-10">
                    {/* Top Section with improved responsiveness */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 sm:gap-10 mb-8 sm:mb-10">
                        <div>
                            <Link to="/" className="flex items-center gap-2 mb-4 sm:mb-6">
                                <motion.div
                                    whileHover={{ rotate: 360 }}
                                    transition={{ duration: 0.7 }}
                                    className="bg-white rounded-full p-1.5 sm:p-2"
                                >
                                    <FaLightbulb className="text-blue-600 text-base sm:text-lg" />
                                </motion.div>
                                <span className="font-bold text-lg sm:text-xl text-white">
                                    Tech<span className="text-blue-300">Insights</span>AI
                                </span>
                            </Link>
                            <p className="text-gray-300 mb-5 sm:mb-6 text-sm sm:text-base">
                                Discover the latest insights in technology, generated by AI and curated for tech enthusiasts and forward-thinkers.
                            </p>
                        </div>
                        <motion.div
                            variants={container}
                            initial="hidden"
                            whileInView="show"
                            viewport={{ once: true }}
                            className="col-span-1 md:col-span-3"
                        >
                            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 sm:gap-8">
                                {footerLinks.map((column, idx) => (
                                    <div key={idx}>
                                        <h3 className="font-semibold text-base sm:text-lg mb-3 sm:mb-4 text-white">{column.title}</h3>
                                        <ul className="space-y-2 sm:space-y-3">
                                            {column.links.map((link, linkIdx) => (
                                                <motion.li key={linkIdx} variants={item}>
                                                    <Link
                                                        to={link.path}
                                                        className="text-gray-300 hover:text-blue-300 transition-colors flex items-center gap-2 text-sm sm:text-base"
                                                    >
                                                        {link.icon && <span>{link.icon}</span>}
                                                        {link.name}
                                                    </Link>
                                                </motion.li>
                                            ))}
                                        </ul>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    </div>

                    {/* Newsletter with improved responsiveness */}
                    <motion.div
                        className="bg-white/5 backdrop-blur-sm rounded-lg sm:rounded-2xl p-4 sm:p-8 mb-8 sm:mb-10"
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.2 }}
                    >
                        <div className="grid md:grid-cols-5 gap-4 sm:gap-6 items-center">
                            <div className="md:col-span-3">
                                <h3 className="text-lg sm:text-xl font-bold mb-1 sm:mb-2">Stay up to date</h3>
                                <p className="text-gray-300 text-sm sm:text-base">Get the latest tech insights delivered straight to your inbox.</p>
                            </div>
                            <div className="md:col-span-2">
                                <form className="flex" onSubmit={handleSubscribeClick}>
                                    <input
                                        type="email"
                                        placeholder="Enter your email"
                                        className="bg-white/10 text-white rounded-l-lg px-3 sm:px-4 py-2 sm:py-3 flex-grow focus:outline-none focus:ring-2 focus:ring-blue-400 text-sm sm:text-base"
                                    />
                                    <motion.button
                                        type="submit"
                                        whileHover={{ scale: 1.05 }}
                                        whileTap={{ scale: 0.95 }}
                                        className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 sm:py-3 px-4 sm:px-6 rounded-r-lg transition-colors text-sm sm:text-base"
                                    >
                                        Subscribe
                                    </motion.button>
                                </form>
                            </div>
                        </div>
                    </motion.div>

                    {/* Bottom Section with improved responsiveness */}
                    <div className="pt-6 sm:pt-8 border-t border-gray-700/50 flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
                        <p className="text-gray-400 text-xs sm:text-sm">
                            &copy; {new Date().getFullYear()} TechInsights AI. All rights reserved.
                        </p>
                        <div className="flex flex-wrap justify-center gap-4 sm:gap-6">
                            <Link to="#" className="text-gray-400 hover:text-blue-300 text-xs sm:text-sm transition-colors">Privacy Policy</Link>
                            <Link to="#" className="text-gray-400 hover:text-blue-300 text-xs sm:text-sm transition-colors">Terms of Service</Link>
                            <Link to="#" className="text-gray-400 hover:text-blue-300 text-xs sm:text-sm transition-colors">Cookie Policy</Link>
                        </div>
                    </div>
                </div>
            </footer>

            {/* Coming Soon Popup */}
            <ComingSoonPopup isOpen={isPopupOpen} onClose={() => setIsPopupOpen(false)} />
        </>
    );
};

export default Footer;